export const fields = ({
  body,
  fontBold,
  fontLight,
  formatDate,
  formatCNPJ,
  formatValor,
}: any) => [
  { name: "CNPJEmpresa", value: formatCNPJ(body.cnpjEmpresa), font: fontLight, size: 13 },
  { name: "NomeEmpresa", value: body.nomeEmpresa, font: fontBold, size: 17 },
  { name: "RazaoEmpresa", value: body.razaoEmpresa, font: fontLight, size: 13 },
  { name: "Tomador", value: body.nomeTomador, font: fontBold, size: 13 },
  { name: "Email", value: body.emailTomador, font: fontLight, size: 12 },
  { name: "Telefone1Tomador", value: body.telefone1Tomador, font: fontLight, size: 12 },
  { name: "Telefone2Tomador", value: body.telefone2Tomador, font: fontLight, size: 12 },
  { name: "Departamento", value: body.departamentoTomador, font: fontLight, size: 12 },
  { name: "Vendedor", value: body.nomeVendedor, font: fontBold, size: 13 },
  { name: "EmailVendedor", value: body.emailVendedor, font: fontLight, size: 12 },
  { name: "Telefone1Vendedor", value: body.telefone1Vendedor, font: fontLight, size: 12 },
  { name: "Telefone2Vendedor", value: body.telefone2Vendedor, font: fontLight, size: 12 },
  { name: "DepartamentoVendedor", value: body.departamentoVendedor, font: fontLight, size: 12 },
  { name: "TipoContato", value: body.tipoContato, font: fontLight, size: 12 },
  { name: "EntradaProposta", value: formatDate(body.entradaProposta), font: fontBold, size: 12 },
  { name: "DataProposta", value: formatDate(body.dataProposta), font: fontBold, size: 12 },
  { name: "DataFullProposta", value: body.dataFullProposta, font: fontLight, size: 12 },
  { name: "CodigoProposta", value: body.codigoProposta, font: fontBold, size: 13 },
  { name: "ValidadeProposta", value: body.validadeProposta, font: fontLight, size: 12 },
  { name: "ValorDiaria", value: formatValor(body.valorDiaria), font: fontBold, size: 12 },
  { name: "ValorKM", value: formatValor(body.valorKM), font: fontBold, size: 12 },
  { name: "ValorTecnico", value: formatValor(body.valorTecnico), font: fontBold, size: 12 },
  { name: "CondicaoPagamento", value: body.condicaoPagamento, font: fontLight, size: 12 },
];
