export const fields = ({
  body,
  fontBold,
  fontLight,
  formatDate,
  formatCNPJ,
  formatValor,
}: any) => [
  { name: "Vendedor1", value: body.vendedor, font: fontBold, size: 13 },
  { name: "Tomador", value: body.tomador, font: fontLight, size: 12 },
  { name: "Departamento", value: body.departamento, font: fontLight, size: 12 },
  { name: "Email", value: body.email, font: fontLight, size: 10 },
  { name: "Telefone", value: body.telefone, font: fontLight, size: 12 },
  { name: "Data", value: formatDate(body.data), font: fontBold, size: 12 },
  { name: "DataExtensa", value: body.dataFull, font: fontLight, size: 12 },
  { name: "Proposta", value: body.proposta, font: fontBold, size: 13 },
  { name: "Empresa", value: body.nomeEmpresa, font: fontBold, size: 17 },
  { name: "RazaoSocial", value: body.razao, font: fontLight, size: 13 },
  { name: "CNPJ", value: formatCNPJ(body.cnpj), font: fontLight, size: 13 },
  { name: "Potencia", value: `${body.potencia} KVA`, font: fontBold, size: 12 },
  {
    name: "ValorTotal",
    value: formatValor(body.valor),
    font: fontBold,
    size: 12,
  },
  { name: "Vendedor", value: body.vendedor, font: fontLight, size: 12 },
  {
    name: "DepartamentoVendedor",
    value: body.departamentovendedor,
    font: fontLight,
    size: 12,
  },
  {
    name: "EmailVendedor",
    value: body.emailvendedor,
    font: fontLight,
    size: 12,
  },
  {
    name: "Telefone1Vendedor",
    value: body.telefone1vendedor,
    font: fontLight,
    size: 12,
  },
  {
    name: "Telefone2Vendedor",
    value: body.telefone2vendedor,
    font: fontLight,
    size: 12,
  },
  { name: "Meses", value: body.mes, font: fontLight, size: 12 },
  {
    name: "Site",
    value: "www.elosolutions.com.br",
    font: fontLight,
    size: 12,
  },
];
